name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

    flake8_py3:
      runs-on: ubuntu-latest
      steps:
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.10
            architecture: x64
        - name: Checkout PyTorch
          uses: actions/checkout@main
        - name: Install flake8
          run: pip install flake8
        - name: Run flake8
          uses: suo/flake8-github-action@releases/v1
          with:
            checkName: 'repositorio_git'   # NOTE: this needs to be the same as the job name
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



